version: "3.5"
services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        NOTROOT_USER: ${NOTROOT_USER}
    ports:
      - "2222:22"
    volumes:
      - ../../docker-www:/data/www:rw
    networks:
      - backend
    restart: always

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        NOTROOT_USER: ${NOTROOT_USER}
    ports:
      - "9000:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - ../../docker-www:/data/www:rw
      - ./php/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    networks:
      - backend
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../../docker-www:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ../logs/nginx/:/var/log/nginx
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
    build: ./mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql:rw
      - ../logs/mysql:/var/lib/mysql-logs:rw
      - ./mysql/conf.d:/etc/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      restart:
      command: "--character-set-server=utf8"

  redis-db:
    build: ./redis
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
      - frontend
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY:
      PMA_HOST:
      MYSQL_ROOT_PASSWORD:
    depends_on:
      - mysql-db
    links:
      - mysql-db:mysql
    restart: always

networks:
  frontend:
  backend:
